services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: projectmanagement
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-prootsecret" ]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 25s
    networks: [ appnet ]



  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-spring-app:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/projectmanagement?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      mysql:
        condition: service_healthy
    networks: [ appnet ]


  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - type: bind
        source: /mnt/c/Users/arpit/OneDrive/Desktop/docker/docker/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    depends_on: [ app ]
    networks: [ appnet ]


networks:
  appnet:

volumes:
  mysql_data:
